# Generated by Django 5.0.1 on 2024-01-26 16:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="position",
            options={"ordering": ("name",)},
        ),
        migrations.AlterModelOptions(
            name="tasktype",
            options={"ordering": ("name",)},
        ),
    ]
