# Generated by Django 5.0.1 on 2024-01-26 17:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0002_alter_position_options_alter_tasktype_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="task",
            options={
                "ordering": ("deadline", "priority"),
                "verbose_name": "task",
                "verbose_name_plural": "tasks",
            },
        ),
    ]
