# Generated by Django 5.0.1 on 2024-01-27 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0003_alter_task_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="task",
            options={
                "ordering": ("is_completed", "deadline", "priority"),
                "verbose_name": "task",
                "verbose_name_plural": "tasks",
            },
        ),
    ]
