# Generated by Django 5.0.1 on 2024-02-06 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_alter_task_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ('deadline', 'priority'), 'verbose_name': 'task', 'verbose_name_plural': 'tasks'},
        ),
        migrations.RemoveField(
            model_name='task',
            name='is_completed',
        ),
        migrations.AddField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('to_do', 'To Do'), ('in_progress', 'In progress'), ('reviewing', 'Reviewing'), ('completed', 'Completed')], default='to_do', max_length=30),
        ),
    ]
